apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tetrate-pre-check-tool.fullname" . }}
  labels:
    {{- include "tetrate-pre-check-tool.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - namespaces
  - configmaps
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - deployments
  verbs: ["get", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs: ["get", "list"]
- apiGroups: ["apiextensions.k8s.io"]
  resources:
  - customresourcedefinitions
  verbs: ["get", "list"]
- apiGroups: ["networking.istio.io"]
  resources:
  - virtualservices
  - destinationrules
  - gateways
  - serviceentries
  verbs: ["get", "list"]
- apiGroups: ["security.istio.io"]
  resources:
  - peerauthentications
  - authorizationpolicies
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tetrate-pre-check-tool.fullname" . }}
  labels:
    {{- include "tetrate-pre-check-tool.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tetrate-pre-check-tool.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tetrate-pre-check-tool.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}